name: Benchmark

on:
  push:
    # branches: [ main ]

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

jobs:
  benchmark:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        model:
          - provider: openai
            name: gpt-4o-mini
          - provider: google
            name: gemini-2.0-flash-lite
        module: [data_extractor, scoring, battle, ranking]
    env:
      MODEL: ${{ matrix.model.name }}
      PROVIDER: ${{ matrix.model.provider }}
      MODULE: ${{ matrix.module }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3'
        bundler-cache: true

    - name: Run ${{ matrix.module }}
      run: bin/test ${{ matrix.module }}

    - name: Shows Summary
      run: |
        touch benchmark/latest.md
        echo "| ActiveGenie::Module | Provider | Model | Tests (Total/Success/Fails) | Precision | Duration (s) | Requests | Tokens | Avg. Duration (s) |" >> benchmark/latest.md
        echo "|--- |--- |--- |--- |--- |--- |--- |--- |--- |" >> benchmark/latest.md
        tail -n +2 benchmark/latest.csv | sed 's/,/ | /g' | sed 's/^/| /' | sed 's/$/ |/' >> benchmark/latest.md
        cat benchmark/latest.md >> $GITHUB_STEP_SUMMARY

    - name: Download results
      uses: actions/download-artifact@v4
      continue-on-error: true
      with:
        name: latest-benchmark
        path: benchmark/latest.csv
        merge-multiple: true

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: latest-benchmark
        path: benchmark/latest.csv
        retention-days: 1
        overwrite: true
        if-no-files-found: ignore

  build_report:
    runs-on: ubuntu-latest
    needs: [benchmark]
    steps:
    - name: Download results
      uses: actions/download-artifact@v4
      with:
        name: latest-benchmark
        path: benchmark/latest.csv
        merge-multiple: true
        if-no-files-found: ignore

    - name: Show on summary
      run: cat benchmark/latest.csv >> $GITHUB_STEP_SUMMARY
