name: Benchmark

on:
  push:
    # branches: [ main ]

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
  ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

jobs:
  benchmark:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        model:
          - provider: openai
            name: gpt-4o-mini
          - provider: google
            name: gemini-2.0-flash-lite
          - provider: anthropic
            name: claude-3-5-haiku-20241022
        module: [data_extractor, scoring, battle, ranking]
    env:
      MODEL: ${{ matrix.model.name }}
      PROVIDER: ${{ matrix.model.provider }}
      MODULE: ${{ matrix.module }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3'
        bundler-cache: true

    - name: Run ${{ matrix.module }}
      run: bin/test ${{ matrix.module }}

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: latest-${{ env.MODULE }}-${{ env.PROVIDER }}-${{ env.MODEL }}-benchmark
        path: benchmark/latest-${{ env.MODULE }}-${{ env.PROVIDER }}-${{ env.MODEL }}.csv
        retention-days: 1
        overwrite: true
        if-no-files-found: ignore

  build_report:
    runs-on: ubuntu-latest
    needs: [benchmark]
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: benchmark/artifacts
        
    - name: Build consolidated report
      run: |
        mkdir -p benchmark/reports
        
        # Create header for the consolidated CSV report
        echo "Module,Provider,Model,Tests,Precision,Duration,Requests,Tokens,Avg_Duration" > benchmark/reports/consolidated_report.csv
        
        # Create header for the markdown report
        echo "# Benchmark Results" > benchmark/reports/consolidated_report.md
        echo "" >> benchmark/reports/consolidated_report.md
        echo "| Module | Provider | Model | Tests | Precision | Duration (s) | Requests | Tokens | Avg. Duration (s) |" >> benchmark/reports/consolidated_report.md
        echo "|--------|----------|-------|-------|-----------|--------------|----------|--------|-------------------|" >> benchmark/reports/consolidated_report.md
        
        # Process all CSV files and build the consolidated reports
        find benchmark/artifacts -name "*.csv" -type f | while read -r file; do
          tail "$file" >> benchmark/reports/consolidated_report.csv
          
          line=$(cat "$file")
          IFS=',' read -r module provider model tests precision duration requests tokens avg_duration <<< "$line"
          echo "| $module | $provider | $model | $tests | $precision | $duration | $requests | $tokens | $avg_duration |" >> benchmark/reports/consolidated_report.md
        done
        
        echo "Consolidated reports created:"
        echo "- CSV: benchmark/reports/consolidated_report.csv"
        echo "- Markdown: benchmark/reports/consolidated_report.md"
        
        cat benchmark/reports/consolidated_report.md
        
    - name: Upload consolidated report
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-consolidated-report
        path: benchmark/reports/
        retention-days: 7
