name: Benchmark

on:
  push:
    # branches: [ main ]

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        provider:
          - name: openai
            model: gpt-4o-mini
          # - name: google
          #   model: gemini-2.0-flash-lite
    env:
      MODEL: ${{ matrix.provider.model }}
      PROVIDER: ${{ matrix.provider.name }}
    continue-on-error: true

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3'
        bundler-cache: true
    
    - name: Install dependencies
      run: bundle install

    - name: Run battle tests
      run: bin/test battle

    - name: Run data extractor tests
      run: bin/test data_extractor

    - name: Run ranking tests
      run: bin/test ranking

    - name: Run scoring tests
      run: bin/test scoring

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results
        path: benchmark.md

    - name: Show on summary
      run: cat benchmark.md >> $GITHUB_STEP_SUMMARY
