name: Benchmark

on:
  push:
    branches: [ main ]

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
  ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

jobs:
  benchmark:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        model:
          - provider: openai
            name: gpt-4o-mini
          - provider: google
            name: gemini-2.0-flash-lite
          - provider: anthropic
            name: claude-3-5-haiku-20241022
        module: [data_extractor, scoring, battle, ranking]
    env:
      MODEL: ${{ matrix.model.name }}
      PROVIDER: ${{ matrix.model.provider }}
      MODULE: ${{ matrix.module }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3'
        bundler-cache: true

    - name: Run ${{ matrix.module }}
      run: bin/test ${{ matrix.module }}

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: latest-${{ env.MODULE }}-${{ env.PROVIDER }}-${{ env.MODEL }}-benchmark
        path: benchmark/latest-${{ env.MODULE }}-${{ env.PROVIDER }}-${{ env.MODEL }}.csv
        retention-days: 1
        overwrite: true
        if-no-files-found: ignore

  # build_report:
  #   runs-on: ubuntu-latest
  #   needs: [benchmark]
  #   steps:
  #   - name: Download multiple artifacts using a script
  #     run: |

  #       for artifact in "latest-${{ env.MODULE }}-${{ env.PROVIDER }}-${{ env.MODEL }}-benchmark"; do
  #         gh run download --name "$artifact" --dir "artifacts/$artifact"
  #       done
  #     env:
  #       GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  #   - name: Shows Summary
  #     run: |
  #       touch benchmark/latest.md
  #       echo "| ActiveGenie::Module | Provider | Model | Tests (Total/Success/Fails) | Precision | Duration (s) | Requests | Tokens | Avg. Duration (s) |" >> benchmark/latest.md
  #       echo "|--- |--- |--- |--- |--- |--- |--- |--- |--- |" >> benchmark/latest.md
  #       cat benchmark/latest.csv | sed 's/,/ | /g' | sed 's/^/| /' | sed 's/$/ |/' >> benchmark/latest.md
  #       cat benchmark/latest.md >> $GITHUB_STEP_SUMMARY
