name: Benchmark

on:
  push:
    # branches: [ main ]

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        provider:
          - name: openai
            model: gpt-4o-mini
          - name: google
            model: gemini-2.0-flash-lite
    env:
      MODEL: ${{ matrix.provider.model }}
      PROVIDER: ${{ matrix.provider.name }}
    continue-on-error: true

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3'
        bundler-cache: true

    - name: Run battle
      run: bin/test battle

    - name: Run data extractor
      run: bin/test data_extractor

    - name: Run scoring
      run: bin/test scoring

    - name: Run ranking
      run: bin/test ranking

    - name: Show on summary
      run: cat benchmark/latest.md benchmark/tmp.md >> $GITHUB_STEP_SUMMARY

    - name: Download other results
      uses: actions/download-artifact@v4
      with:
        name: tmp-benchmark
        path: benchmark/tmp.md
        merge-multiple: true
        if-no-files-found: ignore

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: tmp-benchmark
        path: benchmark/tmp.md
        retention-days: 1

  build_report:
    runs-on: ubuntu-latest
    needs: benchmark
    steps:
    - name: Download other results
      uses: actions/download-artifact@v4
      with:
        name: tmp-benchmark
        path: benchmark/tmp.md
        merge-multiple: true
        if-no-files-found: ignore

    - name: Merge results
      run: cat benchmark/latest.md benchmark/tmp.md > benchmark/latest.md
    
    - name: Upload latest results
      uses: actions/upload-artifact@v4
      with:
        name: latest-benchmark
        path: benchmark/latest.md
        retention-days: 30