name: Lint

on:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3'
        bundler-cache: true

    - name: Install dependencies
      run: bundle install

    - name: Run RuboCop
      run: bundle exec rubocop --parallel --format progress --fail-on-warnings
